import React from "react"
import Head from 'next/head'
import Image from 'next/image'
import data from "./../data/MOCK_DATA.json"
import headerimg from "./../public/img/header-img.jpg"


export default function Home() {
  const [persons, setPersons] = React.useState(data)
  const [person, setPerson] = React.useState({first_name: "", last_name: "", email: ""})

  function addPerson(e){
    // e.preventDefault()
    setPersons([...persons, {...person, id: Date.now()}])
    setPerson({first_name: "", last_name: "", email: ""})
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Image width={250} height={150}src={headerimg} alt="preview"/>

      <div className="form-person">
        <input
           value={person.first_name}
           onChange={(e) => setPerson({...person, first_name: e.target.value})}
           placeholder="Enter First Name"
        />
        <input
           value={person.last_name}
           onChange={(e) => setPerson({...person, last_name: e.target.value})}
           placeholder="Enter Last Name"
        />
        <input
           value={person.email}
           onChange={(e) => setPerson({...person, email: e.target.value})}
           placeholder="Enter Email"
        />
        <button onClick={() => addPerson()}>Add Person</button>
      </div>
      
      <div className="persons-list">
        <ul>
          {persons.map((person) => (
             <li key={person.id}>
              <h2>{person.first_name}</h2>
              <h3>{person.last_name}</h3>
              <p>{person.email}</p>
             </li>
          ))}
        </ul>
      </div>
    </div>
  )
}
