import React from "react"
import Head from 'next/head'
import Image from 'next/image'
import data from "./../data/MOCK_DATA.json"
import headerimg from "./../public/img/header-img.jpg"

export const getStaticProps = async () => {
  return {
    props: {persons: data}
  }
}


export default function Home({persons}) {

  const [users, setUsers] = React.useState(persons)

  function removePerson(id){
    setUsers(users.filter(person => person.id !== id))
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Image width={250} height={150}src={headerimg} alt="preview"/>
      
      
      <div className="persons-list">
        <ul>
          {users.length === 0 ? (
          <h1 className="error-message">Person Not Found</h1>
          ) : (
            users.map((person) => (
             <li key={person.id}>
              <h2>{person.first_name}</h2>
              <h3>{person.last_name}</h3>
              <p>{person.email}</p>
              <button onClick={() => removePerson(person.id)}>X</button>
             </li>
          )))}
        </ul>
      </div>
    </div>
  )
}
