import React from "react"
import Head from 'next/head'
import Image from 'next/image'
import data from "./../data/MOCK_DATA.json"
import headerimg from "./../public/img/header-img.jpg"
import Select from "../components/Select"

export const getStaticProps = async () => {
  return {
    props: {persons: data}
  }
}

export default function Home({persons}) {

  const [users, setUsers] = React.useState(persons)
  const [select, setSelect] = React.useState("")

  function selectPersons(sort){
    setSelect(sort)
    setUsers([...users.sort((a, b) => a[sort].localeCompare(b[sort]))])
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Image width={250} height={150}src={headerimg} alt="preview"/>
      
      
        <Select
          value={select}
          selectPersons={selectPersons}
          defaultName="Select"
          options={[
              {value: "first_name", name: "By first name"},
              {value: "last_name", name: "By last name"},
            ]}
          />
      
      
      <div className="persons-list">
        <ul>
          {users.map((person) => (
             <li key={person.id}>
              <h2>{person.first_name}</h2>
              <h3>{person.last_name}</h3>
              <p>{person.email}</p>
              <button onClick={() => removePerson(person.id)}>X</button>
             </li>
          ))}
        </ul>
      </div>
    </div>
  )
}
